name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17 (Ancient Version)
      uses: actions/setup-java@v4        # ğŸ‘ˆ è¿™ä¸€è¡Œåªå†™å·¥å…·å
      with:                              # ğŸ‘ˆ å‚æ•°è¦å†™åœ¨ with ä¸‹é¢
        java-version: '17.0.2'           # ğŸ‘ˆ è¿™é‡ŒæŒ‡å®šå…·ä½“çš„æ—§ç‰ˆæœ¬
        distribution: 'zulu'             # ğŸ‘ˆ æ¨èç”¨ zuluï¼Œå…¼å®¹æ€§æ›´å¥½
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew MixinApk-release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: QQPro
        path: app/dist/QQPro*.apk
